version: "3.7"
services:

  zookeeper:
    extends:
      file: zookeeper/docker-compose.yml
      service: zookeeper
  hbase:
    extends:
      file: hbase/docker-compose.yml
      service: hbase
    links:
      - zookeeper:zk

  kafka:
    extends:
      file: kafka/docker-compose.yml
      service: kafka
    links:
      - zookeeper:zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  kafka-manager:
    extends:
      file: kafka/docker-compose.yml
      service: kafka-manager
    links:
      - zookeeper:zk
      - kafka:kafka

  hadoop:
    extends:
      file: hadoop/docker-compose.yml
      service: hadoop

  pig:
    extends:
      file: hadoop/docker-compose.yml
      service: pig