spring:
  application:
    name: kafka-consumer-stream
  kafka:
    bootstrap-servers: 192.168.99.100:9092
    consumer:
      group-id: twitterworld
    template:
      default-topic: tweets
server:
  port: 9092